EXPORT DEF wMonOrItemNameBuffer EQU $CF72
EXPORT DEF wNewGameResetWIP EQU $D18B
EXPORT DEF wOptions EQU $D1AB
EXPORT DEF wSaveFileExists EQU $D1AC
EXPORT DEF wTextboxFlags EQU $D1AE
EXPORT DEF wOptions2 EQU $D1B0
EXPORT DEF wOptionsEnd EQU $D1B3
EXPORT DEF wStackTop EQU $DFFF
