EXPORT DEF wOverworldDelay EQU $CF1C
EXPORT DEF wTextDelayFrames EQU $CF1D
EXPORT DEF wVBlankOccurred EQU $CF1E
EXPORT DEF wBGP EQU $CF6D
EXPORT DEF wOBP0 EQU $CF6E
EXPORT DEF wOBP1 EQU $CF6F
EXPORT DEF wROMBankBackup EQU $D147

EXPORT DEF hTransferShadowOAM EQU $FF80
